### ISSUE TITLE
Albums endpoint is not working

### ISSUE THREAD

**Issue by colorful-tones** [sarbor/taylor_swift_api#1]
Returns a 404 every time. curl \
 -X GET https://taylor-swift-api.sarbo.workers.dev/albums/2

Thanks for writing this handy API! ❤️

**Comment by sarbor** [comment]
Thanks for reaching out!

We had to shut off some endpoints at that time due to too much traffic!

We are back online, should work now
<img width="580" alt="Screen Shot 2023-12-01 at 11 24 18 PM" src="https://github.com/sarbor/taylor_swift_api/assets/15257226/f3ee91eb-fd69-4ba7-87a3-ce5739a0b456">
