### ISSUE TITLE
Albums/{AlbumID} Not Returning List of Songs

### ISSUE THREAD

**Issue by krh1502** [sarbor/taylor_swift_api#2]
It appears that using the /albums/{albumID} endpoint only returns the entry for that album ID, not the list of songs within that album.

**Comment by sarbor** [comment]
Thanks for the feedback!

This should be good now

<img width="1512" alt="Screenshot 2023-12-11 at 12 42 54 PM" src="https://github.com/sarbor/taylor_swift_api/assets/15257226/86ea7c57-e888-4bf0-8ea8-fd06b2cfb568">
